# -*- coding: utf-8 -*-
"""Create_Train_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KcPRW74RiQAbpl1P8Lhg8JXvSLKmHC_Y
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os
import shutil
import random

def move_random(input_dir, output_dir, percent):
  file_list = [file for file in os.listdir(input_dir) if os.path.isfile(os.path.join(input_dir, file))]
  random_files = random.sample(file_list, int((percent/100)*len(file_list)))
  for file in random_files:
    shutil.move(os.path.join(input_dir, file), output_dir)

move_random('/content/gdrive/My Drive/Arihant/Dataset/drone', '/content/gdrive/My Drive/Arihant/Test_Set/drone', 15)

move_random('/content/gdrive/My Drive/Arihant/Dataset/fighter-jet', '/content/gdrive/My Drive/Arihant/Test_Set/fighter-jet', 15)

move_random('/content/gdrive/My Drive/Arihant/Dataset/helicopter', '/content/gdrive/My Drive/Arihant/Test_Set/helicopter', 15)

move_random('/content/gdrive/My Drive/Arihant/Dataset/missile', '/content/gdrive/My Drive/Arihant/Test_Set/missile', 15)

move_random('/content/gdrive/My Drive/Arihant/Dataset/passenger-plane', '/content/gdrive/My Drive/Arihant/Test_Set/passenger-plane', 15)

move_random('/content/gdrive/My Drive/Arihant/Dataset/rocket', '/content/gdrive/My Drive/Arihant/Test_Set/rocket', 15)